version: '3'
services:
    tomcat:
        build:
            dockerfile: Dockerfile
            context: ./server
        ports:
            - 8088:8080
        restart: always
        container_name: tomcat_dockcomp1
        volumes:
            - mytomcatdata:/opt/tomcat/
volumes:
    mytomcatdata:
